### ISSUE TITLE
trying to run this

### ISSUE THREAD

**Issue by Sophrinix** [yuchi/react-titanium#3]
My app.js and my config.json look exactly the way your readme describes.

```
[ERROR]
/Users/andrewmcelroy/Desktop/reactexample/Resources/app.js:1
import React, { Component } from 'react';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

[ERROR] Project failed to build after 712ms
[ERROR] 'import' and 'export' may appear only with 'sourceType: module'

➜  reactexample
```

I followed your README exactly as directed. 

This is the error I get when I run `ti build --platform=ios`

**Comment by Sophrinix** [comment]
So I turns out that generating the config.json doesn't do the titaniumifier hook.

When I adjust the file to include the titaniifier

```
{
  "name": "reactexample",
  "version": "1.0.0",
  "description": "Welcome to your Appcelerator Titanium Mobile Project",
  "main": "Resources/app.js",
  "titaniumifier": {
    "transforms": {
      "babelify": {
        "stage": 0,
        "optional": [ "runtime" ]
      }
    }
  },
  "dependencies": {
    "babel-runtime": "^5.8.12",
    "babelify": "^6.1.3",
    "react": "^0.14.0-beta1",
    "react-titanium": "^0.1.2",
    "titaniumifier": "^1.4.1"
  },
  "devDependencies": {
    "babel-runtime": "^5.8.19",
    "babelify": "^6.1.3",
    "titaniumifier": "^1.4.1"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

I now get:

```
[TRACE] [titaniumifier] File location: /Users/andrewmcelroy/Desktop/reactexample/build/titaniumifier/ios/app_js

/usr/local/lib/node_modules/titanium-code-processor/node_modules/es6-shim/es6-shim.js:682
              throw new TypeError('cannot set prototype on a non-object');
                    ^
TypeError: cannot set prototype on a non-object
    at defineProperties.setPrototypeOf.checkArgs (/usr/local/lib/node_modules/titanium-code-processor/node_modules/es6-shim/es6-shim.js:682:21)
    at defineProperties.setPrototypeOf.setPrototypeOf (/usr/local/lib/node_modules/titanium-code-processor/node_modules/es6-shim/es6-shim.js:690:13)
    at _inherits (/Users/andrewmcelroy/Desktop/reactexample/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/index.js:14:422)
    at /Users/andrewmcelroy/Desktop/reactexample/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/index.js:31:3
    at Object.<anonymous> (/Users/andrewmcelroy/Desktop/reactexample/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/index.js:74:3)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/andrewmcelroy/Desktop/reactexample/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/index.js:9:15)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Module._load (module.js:312:12)
```

**Comment by Sophrinix** [comment]
is there a specific version of titanium I should run this with?
I am using `4.0.0.GA`

**Comment by yuchi** [comment]
Could you see if #2 solves your issue?

**Comment by yuchi** [comment]
I usually don't use `titanium-code-processor`. Could you deactivate it?

**Comment by Sophrinix** [comment]
it turned out that my node version was still 0.10.x not sure how. This works now. I did notice that `titanium-code-processor` has a very out of date es6-shim.

**Comment by yuchi** [comment]
Thank you @Sophrinix I just came across the same issue :) reported back to appc
